version: '3.0'
services:
  app:
    build:
      context: ./
    image: ${APPNAME}:${TAG_VERSION}
    container_name: ${APPNAME}_${TAG_VERSION}
    hostname: ${APPNAME}
    command: "tail -f /dev/null"
