FROM continuumio/miniconda3:latest
MAINTAINER Lhacker <starclown1@gmail.com>

RUN set -x && \
: install BeautifulSoup && \
  pip install beautifulsoup4 && \
: install Selenium WebDriver && \
  pip install selenium && \
  :
