version: '3.0'
services:
  webapp:
    build:
      context: ./rcxxxxi
    image: ${RCXXXXI_WEBAPP_IMAGE_NAME}:${RCXXXXI_IMAGE_TAG}
    container_name: rcxxxxi-webapp
    hostname: rcxxxxi-webapp
    privileged: true
    links:
      - database
    ports:
      - "19080:80"
      - "19443:443"
    env_file:
      - .env
    volumes:
      - ./rcxxxxi/:${WEBAPP_ROOT}/${WEBAPP_NAME}/
    command:
      - /sbin/init
  database:
    build:
      context: ./dockerfile/mysql
    image: ${RCXXXXI_MYSQL_IMAGE_NAME}:${RCXXXXI_IMAGE_TAG}
    hostname: rcxxxxi-database
    privileged: true
    env_file:
      - .env
    container_name: rcxxxxi-database
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
