version: '3.0'
services:
  webapp:
    build:
      context: ./rcxxxxi/dockerfile
      args:
        WEBAPP_ROOT: ${WEBAPP_ROOT}
        WEBAPP_NAME: ${WEBAPP_NAME}
    image: ${RCXXXXI_WEBAPP_IMAGE_NAME}:${RCXXXXI_IMAGE_TAG}
    container_name: ${RCXXXXI_WEBAPP_CONTAINER_NAME}
    hostname: ${RCXXXXI_WEBAPP_CONTAINER_NAME}
    privileged: true
    networks:
      - rcxxxxi-network
    ports:
      - "127.0.0.1:19080:80"
      - "127.0.0.1:19443:443"
    env_file:
      - .env
    volumes:
      - ./rcxxxxi/:${WEBAPP_ROOT}/${WEBAPP_NAME}/
    command:
      - /sbin/init
  database:
    user: "999:999"
    build:
      context: ./dockerfile/mysql
    image: ${RCXXXXI_DB_IMAGE_NAME}:${RCXXXXI_IMAGE_TAG}
    hostname: ${RCXXXXI_DB_CONTAINER_NAME}
    networks:
      - rcxxxxi-network
    env_file:
      - .env
    container_name: ${RCXXXXI_DB_CONTAINER_NAME}
    volumes:
      - ./data:/var/lib/mysql

networks:
  rcxxxxi-network:
      driver: bridge
