version: '3.0'
services:
  webapp:
    build:
      context: ./rcxxxxi/dockerfile
      args:
        WEBAPP_ROOT: ${WEBAPP_ROOT}
        WEBAPP_NAME: ${WEBAPP_NAME}
    image: ${RCXXXXI_WEBAPP_IMAGE_NAME}:${RCXXXXI_IMAGE_TAG}
    container_name: ${RCXXXXI_WEBAPP_CONTAINER_NAME}
    hostname: ${RCXXXXI_WEBAPP_CONTAINER_NAME}
    privileged: true
    links:
      - database
    ports:
      - "19080:80"
      - "19443:443"
    env_file:
      - .env
    volumes:
      - ./rcxxxxi/:${WEBAPP_ROOT}/${WEBAPP_NAME}/
    command:
      - /sbin/init
  database:
    user: "999:999"
    build:
      context: ./dockerfile/mysql
    image: ${RCXXXXI_MYSQL_IMAGE_NAME}:${RCXXXXI_IMAGE_TAG}
    hostname: ${RCXXXXI_MYSQL_CONTAINER_NAME}
    privileged: true
    env_file:
      - .env
    container_name: ${RCXXXXI_MYSQL_CONTAINER_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
