FROM mysql:5.7
MAINTAINER Lhacker <starclown1@gmail.com>

ENV ROOT_USER_PASSWORD=${ROOT_USER_PASSWORD:-root}
ENV MYSQL_USER=rcawaii
ENV MYSQL_HOST=localhost
ENV MYSQL_PASSWORD=rcawaii

# This is just wrapper of mysql image.
# So, after build, please run init sqls.
