version: '2.0'
services:
  kibana1:
    image: centos:7_kibana_installed_wip
    container_name: kibana1
    privileged: true
    entrypoint: /sbin/init
    ports:
      - "15601:5601"
      - "19200:9200"
  kibana2:
    image: centos:7_kibana_installed_wip
    container_name: kibana2
    privileged: true
    entrypoint: /sbin/init
    ports:
      - "25601:5601"
      - "29200:9200"
  kibana3:
    image: centos:7_kibana_installed_wip
    container_name: kibana3
    privileged: true
    entrypoint: /sbin/init
    ports:
      - "35601:5601"
      - "39200:9200"
